### ISSUE TITLE
Remember Steam login for a longer time

### ISSUE THREAD

**Issue by YorVeX** [sbuggay/vaclist#4]
Right now it seems I have to relogin to Steam every day before I can see my list. Maybe it's because my IP address changed or whether the authentication cookie is only valid for a limited time?

Whatever it is, on other websites with integrated Steam account login (don't want to advertise here, basically all skin trading exchanges I guess) it doesn't happen so often. There my login stays valid for a month or even longer.

**Comment by sbuggay** [comment]
Agreed. I extended expiry from 12 hours to two weeks for now.

**Comment by YorVeX** [comment]
better, thx <3

**Comment by sbuggay** [comment]
@YorVeX there was actually even a bug with this implementation. I switched to stateless auth and made the expiry one month. Let me know if you have any issues.

**Comment by YorVeX** [comment]
Ever since you responsed here back in July it worked flawlessly, can't remember that I ever had to relogin. ;-)
